### ISSUE TITLE
application crash when direct3d capture fails to init and you press start/stop

### ISSUE THREAD

**Issue by CreamyG31337** [TeamAntumbra/wintumbra#11]
I put the exe I want to capture, I start the exe, I press start. Everything looks fine except LED is off. If I then press stop or start I get:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DirectXScreenCapture.Direct3DCapture.Stop()
   at Antumbra.Glow.ExtensionFramework.GlowScreenDriverCoupler.Stop()
   at Antumbra.Glow.ExtensionFramework.ExtensionManager.Stop()
   at Antumbra.Glow.AntumbraCore.Stop(Int32 id)
   at Antumbra.Glow.Settings.SettingsWindow.stopBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPt

**Comment by walshie4** [comment]
Fixed in 02106c897dff3544f1ec873f386ee5251e6680c8 will now return message of extensions not starting correctly. Soon to also send message from extension who failed with said exception. Will close once that has been implemented and pushed.

**Comment by walshie4** [comment]
Extensions can now send messages directly to the user via toolbar notification or directly to the logger.
