### ISSUE TITLE
Crash upon Glow start post sleep / lock wakeup

### ISSUE THREAD

**Issue by DavisFoster** [TeamAntumbra/wintumbra#12]
After resuming from lock / sleep on Win7, the application doesn't automatically restart Glows, and upon attempting to manually start, crashes.  Attempting to ignore the exception causes the application to hang.

*************\* Exception Text **************
System.ObjectDisposedException: The task has been disposed.
   at System.Threading.Tasks.Task.ThrowIfDisposed()
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Antumbra.Glow.Connector.OutputLoop.Stop()
   at Antumbra.Glow.Connector.OutputLoop.Dispose()
   at Antumbra.Glow.AntumbraCore.Stop(Int32 id)
   at Antumbra.Glow.AntumbraCore.StartCurrent()
   at Antumbra.Glow.AntumbraCore.startToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.296 (RTMGDR.030319-2900)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

Antumbra
    Assembly Version: 0.1.20.0
    Win32 Version: 0.1.20.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Antumbra/Antumbra.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1002 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1001 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1001 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

AntumbraFastScreenProcessor.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/ANTUMBRAFASTSCREENPROCESSOR.GLOW.DLL

AntumbraScreenGrabber.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/ANTUMBRASCREENGRABBER.GLOW.DLL

AntumbraSmartScreenProcessor.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/ANTUMBRASMARTSCREENPROCESSOR.GLOW.DLL

Brightener.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/BRIGHTENER.GLOW.DLL

ColorClock.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/COLORCLOCK.GLOW.DLL

DirectXScreenCapture.glow
    Assembly Version: 0.1.0.1
    Win32 Version: 0.1.0.1
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/DIRECTXSCREENCAPTURE.GLOW.DLL

ExampleGlowDriver.glow
    Assembly Version: 0.1.0.1
    Win32 Version: 0.1.0.1
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/EXAMPLEGLOWDRIVER.GLOW.DLL

FluxCompanion.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/FLUXCOMPANION.GLOW.DLL

HSVFade.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/HSVFADE.GLOW.DLL

ManualColorSelector.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/MANUALCOLORSELECTOR.GLOW.DLL

Saturator.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/SATURATOR.GLOW.DLL

SinFade.glow
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/PROGRAM%20FILES%20(X86)/ANTUMBRA/EXTENSIONS/SINFADE.GLOW.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR

**Comment by walshie4** [comment]
Should be fixed as of 4e017526f777ac07d474e95ce5d273d59826a14a.
