### ISSUE TITLE
Fast switching drivers

### ISSUE THREAD

**Issue by Austinh100** [TeamAntumbra/wintumbra#5]
Switching through all of the different drivers, through sin fade, (hitting start after it starts stopping the device) it appears to get stuck on the "Example Glow Driver" after a bit (observed on the glow not in the actual interface) and if you then select the "Color Clock" and then the default "Glow Screen Driver Coupler" you will get this error:

*************\* Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Antumbra.Glow.Utility.FPSCalc.CalcAverageTick(Int64 newtick)
   at Antumbra.Glow.Utility.FPSCalc.Tick()
   at Antumbra.Glow.Connector.OutputLoop.Antumbra.Glow.ExtensionFramework.AntumbraColorObserver.NewColorAvail(Color newColor, EventArgs args)
   at Antumbra.Glow.ExtensionFramework.ExtensionManager.NewColorAvail.Invoke(Color newColor, EventArgs args)
   at Antumbra.Glow.ExtensionFramework.ExtensionManager.Antumbra.Glow.ExtensionFramework.AntumbraColorObserver.NewColorAvail(Color newColor, EventArgs args)
   at ExampleGlowDriver.ExampleGlowDriver.NewColorAvail.Invoke(Color newColor, EventArgs args)
   at ExampleGlowDriver.ExampleGlowDriver.target()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ExampleGlowDriver.ExampleGlowDriver.Stop()
   at Antumbra.Glow.ExtensionFramework.ExtensionManager.Stop()
   at Antumbra.Glow.AntumbraCore.Stop(Int32 id)
   at Antumbra.Glow.Settings.SettingsWindow.extTable_CellContentClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellContentClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCommonCellContentClick(Int32 columnIndex, Int32 rowIndex, Boolean doubleClick)
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Antumbra.Glow.Utility.FPSCalc.CalcAverageTick(Int64 newtick)
   at Antumbra.Glow.Utility.FPSCalc.Tick()
   at Antumbra.Glow.Connector.OutputLoop.Antumbra.Glow.ExtensionFramework.AntumbraColorObserver.NewColorAvail(Color newColor, EventArgs args)
   at Antumbra.Glow.ExtensionFramework.ExtensionManager.NewColorAvail.Invoke(Color newColor, EventArgs args)
   at Antumbra.Glow.ExtensionFramework.ExtensionManager.Antumbra.Glow.ExtensionFramework.AntumbraColorObserver.NewColorAvail(Color newColor, EventArgs args)
   at ExampleGlowDriver.ExampleGlowDriver.NewColorAvail.Invoke(Color newColor, EventArgs args)
   at ExampleGlowDriver.ExampleGlowDriver.target()
   at System.Threading.Tasks.Task.InnerInvoke()

**Comment by walshie4** [comment]
Should be fixed by the above commit, I'll close it later when I push an update with this fix.

**Comment by walshie4** [comment]
Should be fixed in [V0.1.19](https://github.com/TeamAntumbra/wintumbra/releases/tag/V0.1.19-beta).
